---

-
 
  hosts: centos1
  gather_facts: False
 
  vars:
    inline_named_list:
      [ item1, item2, item3, item4 ]
 
  tasks:
    - name: Test inline named list
      debug:
        msg: "{{ inline_named_list }}"
 
    - name: Test inline named list first item dot notation
      debug:
        msg: "{{ inline_named_list.0 }}"
 
    - name: Test inline named list first item brackets notation
      debug:
        msg: "{{ inline_named_list[0] }}"
 
...
