---

-
 
  hosts: linux

  tasks:
    - name: Removing user
      user:
        name: "{{ item }}"
        state: absent
      with_items: 
        - james
        - hayley
        - lily
        - anwen
 
...
