---

-
 
  hosts: centos1
  gather_facts: False
 
  vars:
    named_list:
      - item1
      - item2
      - item3
      - item4
 
  tasks:
    - name: Test named list
      debug:
        msg: "{{ named_list }}"
 
    - name: Test named list first item dot notation
      debug:
        msg: "{{ named_list.0 }}"
 
    - name: Test named list first item brackets notation
      debug:
        msg: "{{ named_list[0] }}"
 
...
